---
readinessProbe:
  exec:
    command:
    - /usr/libexec/check-container
  initialDelaySeconds: 5
  timeoutSeconds: 1
livenessProbe:
  exec:
    command:
    - /usr/libexec/check-container
    - --live
  initialDelaySeconds: 120
  timeoutSeconds: 10
