openapi: "3.0.0"

info:
  title: VMaaS Webapp Utilities
  version: {{ vmaas_version }}

servers: 
  - url: /api

paths:
  /v1/health:
    get:
      summary: Returns avaiability of the api.
      operationId: vmaas.webapp_utils.health.GetHealth.get
      responses:
        200:
          description: API is OK.
          content:
            application/json:
              schema:
                type: object
                properties:
                  health:
                    type: string
                    description: Health of the API.
      tags:
        - default
    
  /v1/packages:
    post:
      summary: Get details about packages, "package_list" must be a list of package NEVRAs.
      operationId: vmaas.webapp_utils.packages.Packages.post
      responses:
        200:
          description: Return details about list of package NEVRAs
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/PackagesReponse'
      requestBody:
        description: Input JSON with list of NEVRA.
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/NevraList'
      tags:
        - packages

  /v1/packages/{Nevra}:
    get:
      summary: Get details about package.
      operationId: vmaas.webapp_utils.packages.Packages.get
      responses:
        200:
          description: Return details about package NEVRA.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/PackagesReponse'
      parameters:
        - $ref: '#/components/parameters/Nevra'
      tags:
        - packages
  
  /v1/packages/repositories/{Nevra}:
    get:
      summary: Get list of repositories where package belong to.
      operationId: vmaas.webapp_utils.package_repositories.PackageRepositories.get
      responses:
        200:
          description: Return repositories list based on given single NEVRA.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/PackageRepositories'
      parameters:
        - $ref: '#/components/parameters/Nevra'
      tags:
        - packages

  /v1/packages/repositories/:
    post:
      summary: Get list of repositories where the packages belong to.
      operationId: vmaas.webapp_utils.package_repositories.PackageRepositories.post
      responses:
        200:
          description: Return repositories list based on given NEVRAs.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/PackageRepositories'
      requestBody:
        description: Input JSON with list of NEVRA.
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/NevraList'
      tags:
        - packages
  /v1/errata:
    post:
      summary: Errata details.
      description: Get details about errata. "errata_list" parameter can be either a list of errata names OR a single POSIX regular expression.
      operationId: vmaas.webapp_utils.errata.Errata.post
      responses:
        200:
          description: Return details about list of errata.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/ErrataResponse'
      requestBody:
        description: Input JSON.
        required: true
        content:
          application/vnd.api+json:
            schema: 
              oneOf:
                - $ref: '#/components/schemas/ErrataList'
                - $ref: '#/components/schemas/ErrataSearch'
      tags:
        - errata

  /v1/errata/{erratum}:
    get:
      summary: Errata details.
      description: Get details about errata. It is possible to use POSIX regular expression as a pettern for errata names.
      operationId: vmaas.webapp_utils.errata.Errata.get
      responses:
        200:
          description: Return details about errata.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/ErrataResponse'
      parameters:
        - $ref: '#/components/parameters/erratum'
      tags:
        - errata

components:
  parameters:
    Nevra:
      name: Nevra
      in: path
      description: Input NEVRA
      required: true
      schema:
        type: string
      example: kernel-2.6.32-696.20.1.el6.x86_64
    erratum:
      name: erratum
      in: path
      description: Errata advisory name or POSIX regular expression patter.
      required: true
      schema:
        type: string
      example: RHSA-2018:0512

  schemas:
    PackagesReponse:
      type: object
      properties:
        summary:
          type: string
          description: Summary of the package
        description:
          type: string
          description: Description of the package
        source_package:
          type: string
          example: kernel
        binary_package_list:
          type: array
          items:
            type: string
            example: kernel
        repositories:
          type: array
          items:
            type: object
            properties:
              label:
                type: string
                example: rhel-6-server-rpms
              name:
                type: string
                example: Red Hat Enterprise Linux 6
              basearch:
                type: string
                example: x86_64
              releasever:
                type: string
                example: 6.9

    NevraList:
      type: object
      required:
        - package_list
      properties:
        package_list:
          type: array
          minItems: 1
          items:
            type: string
            example: kernel-2.6.32-696.20.1.el6.x86_64
    
    PackageRepositories:
      type: object
      properties:
        data:
          type: object
          additionalProperties:
            type: array
            items:
              type: object
              properties:
                repo_name:
                  type: string
                  example: Red Hat Enterprise Linux 6 Desktop (RPMs)
                label:
                  type: string
                  example: rhel-6-desktop-rpms
    ErrataResponse:
      type: object
      properties:
        errata_list:
          type: object
          properties:
            updated:
              type: string
              example: 2018-03-13T17:31:41+00:00
            severity:
              type: string
              example: Important
            reference_list:
              type: array
              items:
                type: string
                example: classification-RHSA2018:0512
            issued:
              type: string
              example: 2018-03-13T17:31:28+00:00
            description:
              type: string
              example: description text
            solution:
              type: string
              example: solution text
            url:
              type: string
              example: https://access.redhat.com/errata/RHSA-2018:0512
            synopsis:
              type: string
              example: Important:kernel security and bug fix update
            cve_list:
              type: array
              items:
                type: string
                example: CVE-2017-5715
            bugzilla_list:
              type: array
              items:
                type: string
                example: 1519778
            package_list:
              type: array
              items: 
                type: string
                example: kernel-2.6.32-696.23.1.el6.x86_64
            source_package_list:
              type: array
              items:
                type: string
                example: kernel-2.6.32-696.23.1.el6.src
            type:
              type: string
              example: security
        modified_since:
          type: string
          example: 2018-04-05T01:23:45+02:00

    ErrataList:
      type: object
      required:
        - errata_list
      properties:
        errata_list:
          type: array
          items:
            type: string
            example: RHSA-2018:0512
        modified_since:
          type: string
          example: 2018-04-05T01:23:45+02:00
      
    ErrataSearch:
      type: object
      required:
        - errata_search
      properties:
        errata_search:
          type: string
          example: RHSA-2018:05
        modified_since:
          type: string
          example: 2018-04-05T01:23:45+02:00

