apiVersion: v1
kind: Template
metadata:
  name: vmaas-${RELEASE}

parameters:
- name: RELEASE
  description: Release of this component
  value: '1'

objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations: {}
    creationTimestamp: null
    labels:
      app: vmaas
    name: vmaas-apidoc
  spec:
    ports:
    - {name: '8000', port: 8000, targetPort: 8080}
    selector:
      component: vmaas-apidoc-${RELEASE}
  status:
    loadBalancer: {}
