apiVersion: v1
kind: Template
metadata:
  name: vmaas-${RELEASE}

parameters:
- name: RELEASE
  description: Release of this component
  value: '1'

objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      prometheus.io/path: /metrics
      prometheus.io/port: '8081'
      prometheus.io/scrape: "true"
    creationTimestamp: null
    labels:
      app: vmaas
    name: vmaas-reposcan
  spec:
    ports:
    - {name: '8081', port: 8081, targetPort: 8081}
    - {name: '8730', port: 8730, targetPort: 8730}
    selector:
      component: vmaas-reposcan-${RELEASE}
  status:
    loadBalancer: {}
