apiVersion: v1
kind: Template
metadata:
  name: vmaas-${RELEASE}

parameters:
- name: RELEASE
  description: Release of this component
  value: '1'

objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      prometheus.io/path: /metrics
      prometheus.io/port: '8080'
      prometheus.io/scrape: "true"
    creationTimestamp: null
    labels:
      app: vmaas
    name: vmaas-webapp
  spec:
    ports:
    - {name: '8080', port: 8080, targetPort: 8080}
    selector:
      component: vmaas-webapp-${RELEASE}
  status:
    loadBalancer: {}
