version: '3.4'
services:
  vmaas_database:
    container_name: vmaas-database
    image: docker.io/library/postgres:12
    restart: unless-stopped
    environment:
      POSTGRES_DB: vmaas
      POSTGRES_USER: vmaas_admin
      POSTGRES_PASSWORD: vmaas_admin_pwd
    ports:
      - 5432:5432

  test:
    container_name: vmaas-webapp
    hostname: vmaas-webapp
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VAR_RPMS: "findutils"
        VAR_PIPENV_INSTALL_OPT: "--dev"
        PIPENV_CHECK: "${PIPENV_CHECK:-1}"
    image: vmaas/app:latest
    stdin_open: true
    tty: true
    environment:
      CI: "${CI:-false}"
      GITHUB_ACTIONS: "${GITHUB_ACTIONS:-false}"
      GITHUB_REF: "${GITHUB_REF:-}"
      GITHUB_HEAD_REF: "${GITHUB_HEAD_REF:-}"
      GITHUB_SHA: "${GITHUB_SHA:-}"
      GITHUB_REPOSITORY: "${GITHUB_REPOSITORY:-}"
      GITHUB_RUN_ID: "${GITHUB_RUN_ID:-}"
    env_file:
      - ./conf/test.env
    depends_on:
      - vmaas_database
    volumes:
      - ./:/vmaas
    user: root
    security_opt:
      - label=disable
