version: '2'
services:
  database:
    container_name: vmaas_database
    build: ./database
    image: vmaas_database_img
    restart: unless-stopped
    env_file:
      - ./docker-compose.env
    ports:
      - 5432:5432

  reposcan:
    container_name: vmaas_reposcan
    build: ./reposcan
    image: vmaas_reposcan_img
    restart: unless-stopped
    env_file:
      - ./docker-compose.env
    depends_on:
      - database
    links:
      - database

  webapp:
    container_name: vmaas_webapp
    build: ./webapp
    image: vmaas_webapp_img
    restart: unless-stopped
    env_file:
      - ./docker-compose.env
    ports:
      - 8080:8080
    depends_on:
      - database
    links:
      - database
