version: '3'
services:
  database:
    labels:
      kompose.volume.size: 1Gi
    container_name: vmaas-database
    build: ./database
    image: vmaas/database
    restart: unless-stopped
    env_file:
      - ./docker-compose.env
    ports:
      - 5432:5432
    volumes:
      - vmaas-db-data:/var/lib/pgsql/data

  reposcan:
    container_name: vmaas-reposcan
    build: ./reposcan
    image: vmaas/reposcan
    restart: unless-stopped
    env_file:
      - ./docker-compose.env
    ports:
      - 8081:8081
    depends_on:
      - database
    links:
      - database

  webapp:
    container_name: vmaas-webapp
    build: ./webapp
    image: vmaas/webapp
    restart: unless-stopped
    env_file:
      - ./docker-compose.env
    ports:
      - 8080:8080
    depends_on:
      - database
    links:
      - database
volumes:
  vmaas-db-data:
