FROM centos:7

# all environment variables are defined in conf/*.env
# only VMAAS_VERSION is here because we want it to be hardcoded in the image
ENV VMAAS_VERSION=latest

RUN yum -y update \
    && yum -y install centos-release-scl \
    && yum -y install rh-python36 postgresql postgresql-libs rsync \
    && rm -rf /var/cache/yum/*

ENV APPBASEDIR=/reposcan

# copy application to directory in a container
ADD $APPBASEDIR/*.sh $APPBASEDIR/
ADD $APPBASEDIR/*.py $APPBASEDIR/
ADD $APPBASEDIR/common/*.py $APPBASEDIR/common/
ADD $APPBASEDIR/database/*.py $APPBASEDIR/database/
ADD $APPBASEDIR/download/*.py $APPBASEDIR/download/
ADD $APPBASEDIR/nistcve/*.py $APPBASEDIR/nistcve/
ADD $APPBASEDIR/redhatcve/*.py $APPBASEDIR/redhatcve/
ADD $APPBASEDIR/repodata/*.py $APPBASEDIR/repodata/
ADD $APPBASEDIR/rsyncd.conf /etc/
ADD scl-enable.sh $APPBASEDIR/

RUN install -d -m 775 -g root /data
RUN adduser --gid 0 -d $APPBASEDIR --no-create-home -c 'VMAAS user' vmaas

RUN $APPBASEDIR/scl-enable.sh pip install --upgrade pip

RUN $APPBASEDIR/scl-enable.sh pip install prometheus-client psycopg2-binary tornado requests "apispec==0.39.0" python-dateutil

USER vmaas

EXPOSE 8081 8730

CMD ["sh", "-c", "$APPBASEDIR/scl-enable.sh $APPBASEDIR/entrypoint.sh"]
