FROM python:3.6.8-stretch

RUN apt-get update -y && \
    apt-get install -y postgresql libpq-dev && \
    rm -rf /var/lib/apt/lists/*

ADD . /vmaas

RUN pip install --upgrade pip && \
    pip install -r /vmaas/reposcan/requirements.txt && \
    pip install -r /vmaas/webapp/requirements.txt && \
    pip install -r /vmaas/websocket/requirements.txt && \
    pip install -r /vmaas/requirements_tests.txt

RUN chown -R postgres:postgres /vmaas

USER postgres
