FROM fedora:28

RUN dnf install -y python3 python3-pip postgresql-server findutils git which && \
    pip3 install --upgrade pipenv pip

# for testing.posgres python package to find postgres commands
RUN ln -s /usr/bin/initdb /usr/local/bin/initdb && \
    ln -s /usr/bin/postgres /usr/local/bin/postgres

RUN mkdir -p /vmaas/webapp /vmaas/reposcan /vmaas/websocket /vmaas/webapp_utils && \
    chown -R postgres:postgres /vmaas

USER postgres

ADD /webapp/Pipfile*       /vmaas/webapp/
ADD /reposcan/Pipfile*     /vmaas/reposcan/
ADD /websocket/Pipfile*    /vmaas/websocket/
ADD /webapp_utils/Pipfile* /vmaas/webapp_utils/
ADD Pipfile*               /vmaas/
ADD /database/upgrade_scripts/* /vmaas/reposcan/database/upgrade_scripts/

ENV LC_ALL=en_US.utf8
ENV LANG=en_US.utf8
RUN cd /vmaas/webapp && pipenv install --dev && pipenv check && \
    cd /vmaas/reposcan && pipenv install --dev && pipenv check && \
    cd /vmaas/websocket && pipenv install --dev && pipenv check && \
    cd /vmaas/webapp_utils && pipenv install --dev && pipenv check && \
    cd /vmaas/ && pipenv install --dev && pipenv check

ADD . /vmaas/

# ensure ownership of all in /vmaas to postgres
USER root
RUN chown -R postgres:postgres /vmaas
USER postgres
