FROM centos:7

RUN yum -y update \
    && yum -y install centos-release-scl \
    && yum -y install rh-python36 \
    && rm -rf /var/cache/yum/*

ENV APPBASEDIR=/websocket

ADD $APPBASEDIR/*.py $APPBASEDIR/
ADD scl-enable.sh $APPBASEDIR/

RUN adduser --gid 0 -d /app --no-create-home -c 'VMAAS user' vmaas

RUN $APPBASEDIR/scl-enable.sh pip install --upgrade pip

RUN $APPBASEDIR/scl-enable.sh pip install tornado

USER vmaas

EXPOSE 8082

CMD ["sh", "-c", "$APPBASEDIR/scl-enable.sh $APPBASEDIR/websocket.py"]
