FROM quay.io/centos/centos:stream10-minimal@sha256:016815593032ee25a50f2fb40be74242ff9b0b2997492c703a34e2f564c1f938

WORKDIR /devserver

COPY requirements.txt /devserver/

RUN microdnf install -y git-daemon nginx subscription-manager python3-pip && \
    microdnf clean all && \
    pip3 install --no-cache-dir -r requirements.txt

COPY vmaas       /devserver/vmaas
COPY devserver/* /devserver/

ENV ACTIVATION_KEY_ORG_ID ""
ENV ACTIVATION_KEY ""
