FROM quay.io/centos/centos:stream10-minimal@sha256:7f18b80974a28ee20d4b56804a5da8982aa756944efc1a76bdf66c8ed68b0af8

WORKDIR /devserver

COPY requirements.txt /devserver/

RUN microdnf install -y git-daemon nginx subscription-manager python3-pip && \
    microdnf clean all && \
    pip3 install --no-cache-dir -r requirements.txt

COPY vmaas       /devserver/vmaas
COPY devserver/* /devserver/

ENV ACTIVATION_KEY_ORG_ID ""
ENV ACTIVATION_KEY ""
