version: '3'

services:
  vmaas_database:
    container_name: vmaas-database
    image: docker.io/library/postgres:12
    restart: unless-stopped
    environment:
      POSTGRES_DB: vmaas
      POSTGRES_USER: vmaas_admin
      POSTGRES_PASSWORD: vmaas_admin_pwd
    ports:
      - 5432:5432
    volumes:
      - vmaas-db-data:/var/lib/pgsql/data

  schema_spy:
    container_name: schema-spy
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile.dbdocs
    depends_on:
      - vmaas_database
    volumes:
      - ./scripts/output:/output
    env_file:
      - ./conf/database-connection-admin.env
    command: java -jar schemaspy.jar
