version: '3'

services:
  vmaas_reposcan:
    depends_on:
      - vmaas_podmanfix
  vmaas_podmanfix:
    container_name: vmaas-podmanfix
    image: vmaas/app:latest
    volumes:
      - vmaas-dump-data:/data:z
    user: root
    command: chown -R vmaas /data
