openapi: '3.0.0'

info:
  title: VMaaS Reposcan
  version: {{ vmaas_version }}

paths:
  /healthz:
    get:
      summary: Application availability
      description: Check whether this application is live
      operationId: vmaas.reposcan.reposcan.HealthHandler.get
      x-methodName: getHealth
      responses:
        200:
          description: Application available
          content:
            text/plain:
              schema:
                type: boolean
                enum: [true, false]
      tags: [ Metadata ]
  /metrics:
    get:
      summary: Application metrics
      description: Return prometheus metrics
      operationId: vmaas.reposcan.reposcan.metrics
      x-methodName: getMetrics
      responses:
        200:
          description: Application metrics
          content:
            text/plain; charset=utf-8:
              schema:
                type: string
      tags: [ Metadata ]
