openapi: '3.0.0'

info:
  title: VMaaS Reposcan
  version: {{ vmaas_version }}

x-format-resps: &format_resps
  400:
    description: Invalid input json format

x-std-resps: &auth_resps
  403:
    description: GitHub personal access token (PAT) was not provided for authorization.

x-running-resp: &running_resp
  429:
    description: Another task is already in progress

x-secured: &secured
  security:
    - ApiKeyAuthAdmin: []

paths:
  /monitoring/health:
    get:
      summary: Application availability
      description: Check whether this application is live
      operationId: vmaas.reposcan.reposcan.HealthHandler.get
      x-methodName: getHealth
      responses:
        200:
          description: Application available
          content:
            text/plain:
              schema:
                type: string
                example: Ok
      tags: [ Metadata ]

  /version:
    get:
      summary: Application version
      operationId: vmaas.reposcan.reposcan.VersionHandler.get
      x-methodName: getVersion
      responses:
        200:
          description: Application version
          content:
            text/plain:
              schema: { type: string, example: '0.0.0'}
      tags: [ Metadata ]

  /repos:
    post:
      summary:  Add repositories to the DB
      operationId: vmaas.reposcan.reposcan.RepoListHandler.post
      <<: *secured
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/AddRepoItem'

      responses: &repo_responses
        200:
          description: Import started
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskStartResponse'
        <<: *running_resp
        <<: *auth_resps
        <<: *format_resps
      tags:
        - Repos

  /repos/git:
    put:
      summary: Add repositories to the DB from git
      operationId: vmaas.reposcan.reposcan.GitRepoListHandler.put
      <<: *secured
      responses:
        <<: *repo_responses
        <<: *running_resp
        <<: *auth_resps
        <<: *format_resps
      tags:
        - Repos

  /repos/git/cleanup:
    delete:
      summary: Delete repositories from the DB if they are not in current repolist
      operationId: vmaas.reposcan.reposcan.GitRepoListCleanupHandler.delete
      <<: *secured
      responses:
        <<: *repo_responses
        <<: *running_resp
        <<: *auth_resps
      tags:
        - Repos

  /repos/{repo}:
    delete:
      summary: Delete repo from the DB
      operationId: vmaas.reposcan.reposcan.RepoDeleteHandler.delete
      <<: *secured
      parameters:
        - name: repo
          description: Repository name or POSIX regular expression pattern
          required: true
          in: path
          x-example: rhel-6-server-rpms OR rhel-[4567]-.*-rpms OR rhel-\d-server-rpms
          schema:
            type: string
      responses:
        <<: *repo_responses
      tags:
        - Repos

  /sync:
    put:
      summary: Sync repositories from git, CVE map and CPE metadata
      operationId: vmaas.reposcan.reposcan.AllSyncHandler.put
      <<: *secured
      responses: &sync_responses
        200:
          description: Sync started
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskStartResponse"
        <<: *running_resp
        <<: *auth_resps
      tags:
        - Sync

  /sync/repo:
    put:
      summary: Sync repositories from imported repolist
      operationId: vmaas.reposcan.reposcan.RepoSyncHandler.put
      <<: *secured
      responses:
        <<: *sync_responses
      tags:
        - Sync

  /sync/cvemap:
    put:
      summary: Sync the CVE map
      operationId: vmaas.reposcan.reposcan.CvemapSyncHandler.put
      <<: *secured
      responses:
        <<: *sync_responses
      tags:
        - Sync

  /sync/cpe:
    put:
      summary: Sync CPE metadata
      operationId: vmaas.reposcan.reposcan.CpeSyncHandler.put
      <<: *secured
      responses:
        <<: *sync_responses
      tags:
        - Sync

  /sync/csaf:
    put:
      summary: Sync CSAF metadata
      operationId: vmaas.reposcan.reposcan.CsafSyncHandler.put
      <<: *secured
      responses:
        <<: *sync_responses
      tags:
        - Sync

  /sync/release:
    put:
      summary: Sync RHEL OS release version metadata
      operationId: vmaas.reposcan.reposcan.ReleaseSyncHandler.put
      <<: *secured
      responses:
        <<: *sync_responses
      tags:
        - Sync

  /export/pkgtree:
    put:
      summary: Export package tree
      operationId: vmaas.reposcan.reposcan.PkgTreeHandler.put
      <<: *secured
      responses:
        <<: *sync_responses
      tags:
        - Export

  /export/dump:
    put:
      summary: Export disk dump
      operationId: vmaas.reposcan.reposcan.ExporterHandler.put
      <<: *secured
      responses:
        200:
          description: Sync started
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskStartResponse"

        <<: *auth_resps
        <<: *running_resp
      tags:
        - Export

  /export/pg_dump:
    put:
      summary: Export pg_dump
      operationId: vmaas.reposcan.reposcan.DbDumpHandler.put
      <<: *secured
      responses:
        200:
          description: Sync started
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskStartResponse"

        <<: *auth_resps
        <<: *running_resp
      tags:
        - Export

  /export/dump_s3:
    put:
      summary: Upload exported dump to S3 bucket
      operationId: vmaas.reposcan.reposcan.S3ExporterHandler.put
      <<: *secured
      responses:
        200:
          description: Sync started
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskStartResponse"

        <<: *auth_resps
        <<: *running_resp
      tags:
        - Export

  /task/status:
    get:
      summary: Get status of currently running background task
      operationId: vmaas.reposcan.reposcan.TaskStatusHandler.get
      responses:
        200:
          description:  Status of currently running background task
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskStatusResponse"
      tags:
        - Task

  /task/cancel:
    put:
      summary: Cancel currently running background task
      operationId: vmaas.reposcan.reposcan.TaskCancelHandler.put
      <<: *secured
      responses:
        200:
          description: Task canceled
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskStatusResponse"
        <<: *auth_resps
      tags:
        - Task

  /dbchange:
    get:
      summary: Information about database sync
      operationId: vmaas.reposcan.reposcan.DbChangeHandler.get
      responses:
        200:
          description: Returns timestamp of last pkgtree export
          content:
            application/json:
              schema:
                $ref:  "#/components/schemas/DbChangeResponse"
      tags:
        - DbChange

  /latestdump:
    get:
      summary: Get latest version of database dump
      operationId: vmaas.reposcan.reposcan.DumpVersionHandler.get
      responses:
        200:
          description: Returns version of latest dump
          content:
            text/plain:
              schema: {type: string, example: "vmaas.dbm-2020-03-30T13:13:46.156455+00:00", nullable: true}
      tags:
        - Metadata

  /cleantmp:
    put:
      summary: Clean /tmp data
      operationId: vmaas.reposcan.reposcan.CleanTmpHandler.put
      <<: *secured
      responses:
        <<: *sync_responses
      tags:
        - Maintenance

  /download/pg_dump:
    get:
      summary: Get pg_dump
      operationId: vmaas.reposcan.reposcan.DbDumpHandler.get
      <<: *secured
      responses:
        200:
          description: Returns pg_dump
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        404:
          description: pg_dump not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error: 
                    type: string
      tags:
        - Download

  /pprof/{param}:
    get:
      summary: Run pprof profiler on webapp-go
      description: |
        Use /pprof/{heap|profile|block|mutex|trace} for profiling,
        see https://pkg.go.dev/net/http/pprof for more info about pprof
      operationId: vmaas.reposcan.reposcan.WebappPprof.get
      parameters:
        - name: param
          in: path
          description: What to profile
          required: true
          schema:
            type: string
            enum:
              - profile
              - heap
              - block
              - mutex
              - trace
      <<: *secured
      responses:
        200:
          description: OK
          content: {}
        <<: *auth_resps
      tags:
        - Debug

components:
  securitySchemes:
    ApiKeyAuthAdmin:
      type: apiKey
      in: header
      name: x-rh-identity
      description: Identity header provided by Turnpike.
      x-apikeyInfoFunc: vmaas.reposcan.reposcan.auth_admin

  schemas:
    CertItem:
      type: object
      properties:
        name:
          type: string
          example: RHSM-CDN
        ca_cert:
          type: string
        cert:
          type: string
        key:
          type: string
      required:
        - name
        - ca_cert

    ProductItem:
      type: object
      properties:
        redhat_eng_product_id:
          type: integer
          example: 69
        content_sets:
          type: object
          additionalProperties:
            oneOf:
              - $ref: '#/components/schemas/ContentItem'
              - type: array
                items:
                  $ref: '#/components/schemas/ContentItem'

      required:
      - content_sets
    ContentItem:
      type: object
      properties:
        name:
          type: string
          example: Red Hat Enterprise Linux 6 Server (RPMs)
        baseurl:
          oneOf:
            - type: string
              example: https://cdn/content/dist/rhel/server/6/$releasever/$basearch/os/
            - type: array
              items:
                type: string
                example: https://cdn/content/dist/rhel/server/6/$releasever/$basearch/os/
        basearch:
          type: array
          items:
            type: string
            example: x86_64
        releasever:
          type: array
          items:
            type: string
            example: 6Server
      required:
        - name
        - baseurl
        - basearch
        - releasever
    AddRepoItem:
      type: object
      properties:
        entitlement_cert:
          oneOf:
            - $ref: '#/components/schemas/CertItem'
            - type: boolean
        products:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/ProductItem'
      required:
      - products
    TaskStatusResponse:
      type: object
      properties:
        running:
          type: boolean
          enum: [true, false]
        task_type:
          type: string
          example: Sync CVEs
          x-nullable: true
      required:
        - running

    TaskStartResponse:
      type: object
      properties:
        success: { type: boolean, enum: [true, false] }
        msg: { type: string, example: 'Repo sync has started' }

    DbChangeResponse:
      type: object
      properties:
        pktree_change: { type: string, format: date-time,  example: '2010-11-10T00:00:00+00:00' }

