REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM vmaas_writer;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM vmaas_reader;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM vmaas_writer;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM vmaas_reader;
DROP USER vmaas_writer;
DROP USER vmaas_reader;
