openapi: "3.0.0"

info:
  title: VMaaS Webapp Utilities
  version: latest

servers: 
  - url: /api

paths:
  /v1/health:
    get:
      summary: Returns avaiability of the api.
      operationId: handlers.default_handler.GetHealth.get
      responses:
        200:
          description: API is OK.
          content:
            application/json:
              schema:
                type: object
                properties:
                  health:
                    type: string
                    description: Health of the API.
