openapi: "3.0.0"

info:
  title: VMaaS Webapp Utilities
  version: {{ vmaas_version }}

paths:
  /healthz:
    get:
      summary: Returns avaiability of the api.
      operationId: health.GetHealth.get
      responses:
        200:
          description: API is OK.
          content:
            application/json:
              schema:
                type: object
                properties:
                  health:
                    type: string
                    description: Health of the API.
      tags:
        - default
