#!/bin/sh

export PIPENV_CHECK=${PIPENV_CHECK:-0}

if [ ! -e /usr/bin/docker-compose ] ; then
    podman-compose ${PODMAN_PATH:+--podman-path=$PODMAN_PATH} \
                        -f docker-compose.yml \
                        -f docker-compose.devel.yml \
                        "$@"
else
    exec docker-compose -f docker-compose.yml -f docker-compose.devel.yml "$@"
fi
