openapi: '3.0.0'

info:
  title: VMaaS Reposcan
  version: {{ vmaas_version }}

paths:
  /healthz:
    get:
      summary: Application availability
      description: Check whether this application is live
      operationId: reposcan.HealthHandler.get
      x-methodName: getHealth
      responses:
        200:
          description: Application available
          content:
            text/plain:
              schema:
                type: boolean
                enum: [true, false]
      tags: [ Metadata ]
