apiVersion: 1

deleteDatasources:
  - name: Insights-Prometheus
    orgId: 1

datasources:
- name: Insights-Prometheus
  type: prometheus
  access: proxy
  orgId: 1
  url: http://vmaas-prometheus:9090
  password:
  user:
  database:
  basicAuth: true
  basicAuthUser: admin
  basicAuthPassword: passwd
  withCredentials:
  isDefault: true
  jsonData:
     graphiteVersion: "1.1"
     tlsAuth: false
     tlsAuthWithCACert: false
  secureJsonData:
    tlsCACert: "..."
    tlsClientCert: "..."
    tlsClientKey: "..."
  version: 1
  editable: true
