apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/RedHatInsights/vmaas?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: 'false'
    pipelinesascode.tekton.dev/max-keep-runs: '3'
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && (target_branch == "master" || target_branch == "hotfix")
    pipelinesascode.tekton.dev/pipeline: https://github.com/RedHatInsights/konflux-pipelines/raw/v1.55.0/pipelines/docker-build-oci-ta.yaml
  creationTimestamp:
  labels:
    appstudio.openshift.io/application: insights-vulnerability
    appstudio.openshift.io/component: vmaas
    pipelines.appstudio.openshift.io/type: build
  name: vmaas-on-push
  namespace: insights-management-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/insights-management-tenant/insights-vulnerability/vmaas:{{revision}}
  - name: dockerfile
    value: Dockerfile
  - name: path-context
    value: .
  - name: hermetic
    value: "true"
  - name: prefetch-input
    value: '[{"type": "pip", "path": ".", "requirements_files": ["requirements.txt", "requirements-build.txt", "requirements-extra.txt"]}, {"type": "rpm", "path": ".hermetic_builds/"}, {"type": "gomod", "path": "./vmaas-go/"}]'
  - name: prefetch-dev-package-managers
    value: "true"
  pipelineRef:
    name: docker-build-oci-ta
  taskRunTemplate:
    serviceAccountName: build-pipeline-vmaas
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
