apiVersion: v1
data:
  GIT_TOKEN: ""
kind: Secret
metadata:
  name: github-vulnerability-bot
type: Opaque

apiVersion: v1
data:
  GIT_TOKEN: ""
kind: Secret
metadata:
  name: github-vmaas-bot
type: Opaque
