apiVersion: v1
kind: Template
metadata:
  name: vmaas-${RELEASE}

parameters:
- name: RELEASE
  description: Release of this component
  value: '1'
- name: GIT_REF
  description: Git reference in repository to build from
  value: master
- name: DOCKERFILE
  description: Dockerfile to build from
  value: reposcan/Dockerfile

objects:
- apiVersion: v1
  data:
    BATCH_MAX_SIZE: '500'
    BATCH_MAX_FILESIZE: '14_000_000_000'
    CHUNK_SIZE: '1048576'
    LOGGING_LEVEL: INFO
    LOGGING_TYPE: OPENSHIFT
    PKGTREE_INDENT: '0'
    PKGTREE_KEEP_COPIES: '2'
    REPOSCAN_SYNC_INTERVAL_MINUTES: '360'
    REPOLIST_GIT: 'https://github.com/RedHatInsights/vmaas-assets.git'
    REPOLIST_PATH: 'repolist.json'
    GIT_COMMITTER_NAME: 'vmaas'
    GIT_COMMITTER_EMAIL: 'vmaas@localhost'

    RETRY_COUNT: '3'
    THREADS: '8'
    YEAR_SINCE: '2002'
    WEBSOCKET_HOST: vmaas-websocket-${RELEASE}
    KEEP_COPIES: '3'
  kind: ConfigMap
  metadata:
    creationTimestamp: null
    labels:
      app: vmaas-${RELEASE}
    name: vmaas-reposcan-conf-reposcan-env-${RELEASE}

- apiVersion: v1
  data:
    POSTGRESQL_DATABASE: vmaas
    POSTGRESQL_HOST: vmaas-database-${RELEASE}
    POSTGRESQL_PASSWORD: vmaas_writer_pwd
    POSTGRESQL_PORT: '5432'
    POSTGRESQL_USER: vmaas_writer
  kind: ConfigMap
  metadata:
    creationTimestamp: null
    labels:
      app: vmaas-${RELEASE}
    name: vmaas-reposcan-conf-database-connection-writer-env-${RELEASE}

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      app: vmaas-${RELEASE}
    name: vmaas-reposcan-tmp-${RELEASE}
  spec:
    accessModes: [ReadWriteOnce]
    resources:
      requests: {storage: 15Gi}
  status: {}

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      app: vmaas-${RELEASE}
    name: vmaas-dump-data-${RELEASE}
  spec:
    accessModes: [ReadWriteOnce]
    resources:
      requests: {storage: 5Gi}
  status: {}

- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations: {}
    creationTimestamp: null
    labels:
      app: vmaas-${RELEASE}
    name: vmaas-reposcan-${RELEASE}
  spec:
    nodeSelector: null
    output:
      to: {kind: ImageStreamTag, name: 'vmaas-reposcan-${RELEASE}:latest'}
    postCommit: {}
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
    runPolicy: Serial
    source:
      git:
        ref: ${GIT_REF}
        uri: 'https://github.com/RedHatInsights/vmaas.git'
      type: Git
    strategy:
      dockerStrategy:
        dockerfilePath: ${DOCKERFILE}
        forcePull: true
      type: Docker
    triggers:
    - {type: ConfigChange}
  status: {lastVersion: 0}

- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    labels:
      app: vmaas-${RELEASE}
    name: vmaas-reposcan-${RELEASE}
  spec:
    tags:
    - name: latest
  status: {dockerImageRepository: ''}

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations: {}
    creationTimestamp: null
    labels:
      app: vmaas-${RELEASE}
      component: vmaas-reposcan-${RELEASE}
    name: vmaas-reposcan-${RELEASE}
  spec:
    replicas: 1
    selector:
      component: vmaas-reposcan-${RELEASE}
    strategy:
      resources: {}
      recreateParams:
        pre:
          failurePolicy: Abort
          execNewPod:
            containerName: vmaas-reposcan
            command:
            - /push_manifest.sh
            - RedHatInsights/manifests
            - stable
            - /reposcan/manifest.txt
            - vmaas/vmaas-reposcan.txt
            env:
            - name: GIT_TOKEN
              valueFrom:
                secretKeyRef:
                  key: GIT_TOKEN
                  name: github-vulnerability-bot
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          component: vmaas-reposcan-${RELEASE}
      spec:
        containers:
        - env:
          - name: BATCH_MAX_SIZE
            valueFrom:
              configMapKeyRef:
                key: BATCH_MAX_SIZE
                name: vmaas-reposcan-conf-reposcan-env-${RELEASE}
          - name: BATCH_MAX_FILESIZE
            valueFrom:
              configMapKeyRef:
                key: BATCH_MAX_FILESIZE
                name: vmaas-reposcan-conf-reposcan-env-${RELEASE}
          - name: CHUNK_SIZE
            valueFrom:
              configMapKeyRef:
                key: CHUNK_SIZE
                name: vmaas-reposcan-conf-reposcan-env-${RELEASE}
          - name: LOGGING_LEVEL
            valueFrom:
              configMapKeyRef:
                key: LOGGING_LEVEL
                name: vmaas-reposcan-conf-reposcan-env-${RELEASE}
          - name: LOGGING_TYPE
            valueFrom:
              configMapKeyRef:
                key: LOGGING_TYPE
                name: vmaas-reposcan-conf-reposcan-env-${RELEASE}
          - name: PKGTREE_INDENT
            valueFrom:
              configMapKeyRef:
                key: PKGTREE_INDENT
                name: vmaas-reposcan-conf-reposcan-env-${RELEASE}
          - name: PKGTREE_KEEP_COPIES
            valueFrom:
              configMapKeyRef:
                key: PKGTREE_KEEP_COPIES
                name: vmaas-reposcan-conf-reposcan-env-${RELEASE}
          - name: POSTGRESQL_DATABASE
            valueFrom:
              configMapKeyRef:
                key: POSTGRESQL_DATABASE
                name: vmaas-reposcan-conf-database-connection-writer-env-${RELEASE}
          - name: POSTGRESQL_HOST
            valueFrom:
              configMapKeyRef:
                key: POSTGRESQL_HOST
                name: vmaas-reposcan-conf-database-connection-writer-env-${RELEASE}
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              configMapKeyRef:
                key: POSTGRESQL_PASSWORD
                name: vmaas-reposcan-conf-database-connection-writer-env-${RELEASE}
          - name: POSTGRESQL_PORT
            valueFrom:
              configMapKeyRef:
                key: POSTGRESQL_PORT
                name: vmaas-reposcan-conf-database-connection-writer-env-${RELEASE}
          - name: POSTGRESQL_USER
            valueFrom:
              configMapKeyRef:
                key: POSTGRESQL_USER
                name: vmaas-reposcan-conf-database-connection-writer-env-${RELEASE}
          - name: REPOSCAN_SYNC_INTERVAL_MINUTES
            valueFrom:
              configMapKeyRef:
                key: REPOSCAN_SYNC_INTERVAL_MINUTES
                name: vmaas-reposcan-conf-reposcan-env-${RELEASE}
          - name: RETRY_COUNT
            valueFrom:
              configMapKeyRef:
                key: RETRY_COUNT
                name: vmaas-reposcan-conf-reposcan-env-${RELEASE}
          - name: THREADS
            valueFrom:
              configMapKeyRef:
                key: THREADS
                name: vmaas-reposcan-conf-reposcan-env-${RELEASE}
          - name: YEAR_SINCE
            valueFrom:
              configMapKeyRef:
                key: YEAR_SINCE
                name: vmaas-reposcan-conf-reposcan-env-${RELEASE}
          - name: WEBSOCKET_HOST
            valueFrom:
              configMapKeyRef:
                key: WEBSOCKET_HOST
                name: vmaas-reposcan-conf-reposcan-env-${RELEASE}
          - name: KEEP_COPIES
            valueFrom:
              configMapKeyRef:
                key: KEEP_COPIES
                name: vmaas-reposcan-conf-reposcan-env-${RELEASE}
          - name: REPOLIST_GIT
            valueFrom:
              configMapKeyRef:
                key: REPOLIST_GIT
                name: vmaas-reposcan-conf-reposcan-env-${RELEASE}
          - name: REPOLIST_PATH
            valueFrom:
              configMapKeyRef:
                key: REPOLIST_PATH
                name: vmaas-reposcan-conf-reposcan-env-${RELEASE}
          - name: REPOLIST_GIT_TOKEN
            valueFrom:
              secretKeyRef:
                key: GIT_TOKEN
                name: github-vmaas-bot
          - name: GIT_COMMITTER_NAME
            valueFrom:
              configMapKeyRef:
                key: GIT_COMMITTER_NAME
                name: vmaas-reposcan-conf-reposcan-env-${RELEASE}
          - name: GIT_COMMITTER_EMAIL
            valueFrom:
              configMapKeyRef:
                key: GIT_COMMITTER_EMAIL
                name: vmaas-reposcan-conf-reposcan-env-${RELEASE}
          - name: DEFAULT_CA_CERT
            valueFrom:
              secretKeyRef:
                key: DEFAULT_CA_CERT
                name: cdn-certificate
          - name: DEFAULT_CERT
            valueFrom:
              secretKeyRef:
                key: DEFAULT_CERT
                name: cdn-certificate
          - name: DEFAULT_KEY
            valueFrom:
              secretKeyRef:
                key: DEFAULT_KEY
                name: cdn-certificate

          image: ' '
          name: vmaas-reposcan
          ports:
          - {containerPort: 8081}
          - {containerPort: 8730}
          resources:
            limits: {cpu: '1', memory: 2Gi}
            requests: {cpu: 200m, memory: 200Mi}
          volumeMounts:
          - mountPath: /tmp
            name: vmaas-reposcan-tmp-${RELEASE}
          - mountPath: /data
            name: vmaas-dump-data-${RELEASE}
          readinessProbe:
            httpGet:
              path: /api/v1/monitoring/health
              port: 8081
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/v1/monitoring/health
              port: 8081
            initialDelaySeconds: 120
            timeoutSeconds: 1
            periodSeconds: 60
        restartPolicy: Always
        volumes:
        - name: vmaas-reposcan-tmp-${RELEASE}
          persistentVolumeClaim:
            claimName: vmaas-reposcan-tmp-${RELEASE}
        - name: vmaas-dump-data-${RELEASE}
          persistentVolumeClaim:
            claimName: vmaas-dump-data-${RELEASE}
    test: false
    triggers:
    - {type: ConfigChange}
    - imageChangeParams:
        automatic: true
        containerNames: [vmaas-reposcan]
        from: {kind: ImageStreamTag, name: 'vmaas-reposcan-${RELEASE}:latest'}
      type: ImageChange
  status: {}

- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      prometheus.io/path: /metrics
      prometheus.io/port: '8081'
      prometheus.io/scrape: "true"
    creationTimestamp: null
    labels:
      app: vmaas-${RELEASE}
    name: vmaas-reposcan-${RELEASE}
  spec:
    ports:
    - {name: '8081', port: 8081, targetPort: 8081}
    - {name: '8730', port: 8730, targetPort: 8730}
    selector:
      component: vmaas-reposcan-${RELEASE}
  status:
    loadBalancer: {}
