apiVersion: v1
kind: Template
metadata:
  name: vmaas-${RELEASE}

parameters:
- name: RELEASE
  description: Release of this component
  value: '1'
- name: GIT_REF
  description: Git reference in repository to build from
  value: master

objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations: {}
    creationTimestamp: null
    labels:
      app: vmaas-${RELEASE}
    name: vmaas-websocket-${RELEASE}
  spec:
    nodeSelector: null
    output:
      to: {kind: ImageStreamTag, name: 'vmaas-websocket-${RELEASE}:latest'}
    postCommit: {}
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
    runPolicy: Serial
    source:
      git:
        ref: ${GIT_REF}
        uri: 'https://github.com/RedHatInsights/vmaas.git'
      type: Git
    strategy:
      dockerStrategy:
        dockerfilePath: Dockerfile-websocket
      type: Docker
    triggers:
    - {type: ConfigChange}
  status: {lastVersion: 0}

- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    labels:
      app: vmaas-${RELEASE}
    name: vmaas-websocket-${RELEASE}
  spec:
    tags:
    - name: latest
  status: {dockerImageRepository: ''}

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations: {}
    creationTimestamp: null
    labels:
      app: vmaas-${RELEASE}
      component: vmaas-websocket-${RELEASE}
    name: vmaas-websocket-${RELEASE}
  spec:
    replicas: 1
    selector:
      component: vmaas-websocket-${RELEASE}
    strategy:
      resources: {}
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          component: vmaas-websocket-${RELEASE}
      spec:
        containers:
        - image: ' '
          name: vmaas-websocket
          ports:
          - {containerPort: 8082}
          resources:
            limits: {cpu: 100m, memory: 100Mi}
            requests: {cpu: 100m, memory: 100Mi}
          readinessProbe:
            httpGet:
              path: /api/v1/monitoring/health
              port: 8082
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/v1/monitoring/health
              port: 8082
            initialDelaySeconds: 120
            timeoutSeconds: 1
            periodSeconds: 60
        restartPolicy: Always
    test: false
    triggers:
    - {type: ConfigChange}
    - imageChangeParams:
        automatic: true
        containerNames: [vmaas-websocket]
        from: {kind: ImageStreamTag, name: 'vmaas-websocket-${RELEASE}:latest'}
      type: ImageChange
  status: {}

- apiVersion: v1
  kind: Service
  metadata:
    annotations: {}
    creationTimestamp: null
    labels:
      app: vmaas-${RELEASE}
    name: vmaas-websocket-${RELEASE}
  spec:
    ports:
    - {name: '8082', port: 8082, targetPort: 8082}
    selector:
      component: vmaas-websocket-${RELEASE}
  status:
    loadBalancer: {}
