FROM centos:7

# all environment variables are defined in conf/reposcan.env
# only VMAAS_VERSION is here because we want it to be hardcoded in the image
ENV VMAAS_VERSION=latest

RUN yum -y install centos-release-scl && \
    yum -y install rh-python36 which rsync procps-ng && \
    rm -rf /var/cache/yum/*

ENV PATH=/opt/rh/rh-python36/root/usr/bin:$PATH

ADD /webapp/Pipfile* /webapp/

ENV LC_ALL=en_US.utf8
ENV LANG=en_US.utf8
RUN pip install --upgrade pip pipenv && \
    cd /webapp && pipenv install --system --dev && pipenv check

RUN install -m 1777 -d /data && \
    adduser --gid 0 -d /webapp --no-create-home vmaas

USER vmaas

ENV COVERAGE_FILE='/tmp/.coverage'

EXPOSE 8080


ADD /webapp/*.spec.yaml /webapp/
ADD /webapp/*.sh        /webapp/
ADD /webapp/*.py        /webapp/
ADD /common/*.py        /webapp/common/

CMD /webapp/entrypoint-qe.sh
