FROM registry.access.redhat.com/ubi8/ubi-minimal

RUN microdnf install python3 which rsync procps-ng shadow-utils tar && microdnf clean all

WORKDIR /webapp

ADD /webapp/Pipfile* /webapp/

ENV LC_ALL=C.utf8
ENV LANG=C.utf8
RUN pip3 install --upgrade pipenv && \
    cd /webapp && pipenv install --ignore-pipfile --deploy --system --dev && ln -s /usr/bin/python3 /usr/bin/python && pipenv check --system

RUN install -m 1777 -d /data && \
    adduser --gid 0 -d /webapp --no-create-home vmaas

USER vmaas

ENV COVERAGE_FILE='/tmp/.coverage'

EXPOSE 8080


ADD /webapp/*.spec.yaml /webapp/
ADD /webapp/*.sh        /webapp/
ADD /webapp/*.py        /webapp/
ADD /common/*.py        /webapp/common/

CMD /webapp/entrypoint-qe.sh
