name: CI

on:
  push:
    branches:
      - 'master'
      - 'stable'
  pull_request:
    branches:
      - 'stable'

jobs:
  integration-tests-local:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cancel previous builds
        uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Docker Login
        uses: Azure/docker-login@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          login-server: quay.io
      - name: Patch reposcan.env with OVAL_FEED_BASE_URL
        run: echo "OVAL_FEED_BASE_URL=https://raw.githubusercontent.com/psegedy/vmaas-data/master/oval/" >> conf/reposcan.env
      - name: Build VMaaS
        run: PIPENV_CHECK=0 docker-compose build
      - name: Run VMaaS
        run: PIPENV_CHECK=0 docker-compose up -d
      - name: Wait for VMaaS to run
        run: |
          set +e
          resp=1
          while [ "$resp" -ne 0 ]; do
            curl http://localhost:8080/healthz
            resp=$?
          done
      - name: Run VMaaS integration tests
        run: |
          docker run --name iqe --network host \
            -e IQE_TESTS_LOCAL_CONF_PATH=/iqe_settings -e ENV_FOR_DYNACONF=smoke \
            ${{ secrets.IQE_TESTS_IMAGE }} \
            iqe tests plugin vmaas -k 'not reconnect' --long-running --html=report.html --self-contained-html
      - run: docker-compose logs > logs
        if: always()
      - run: docker cp iqe:/iqe_venv/report.html .
        if: always()
      - name: Publish test results
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: test-report-local
          path: report.html
      - name: Publish logs
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: docker-compose-logs
          path: logs
