name: golangci-lint
on:
  pull_request:
    paths:
      - vmaas-go/**

jobs:
  golangci:
    name: lint
    strategy:
      matrix:
        go-version: [1.21.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - run: sudo apt install -y librpm-dev rpm
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          working-directory: vmaas-go
