name: golangci-lint
on:
  pull_request:
    branches:
      - "master"
      - "hotfix"
      - 'foreman-*.*'
      - "security-compliance"
    paths:
      - vmaas-go/**

jobs:
  golangci:
    name: lint
    strategy:
      matrix:
        go-version: [1.24.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - run: sudo apt install -y librpm-dev rpm
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8
        with:
          version: latest
          working-directory: vmaas-go
