name: Semantic release

on:
  push:
    branches:
      - "master"

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
        go-version: [1.22]
    steps:
      - name: Cancel previous builds
        uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
          persist-credentials: false # The auth token is persisted in the local git config. semantic-release picks this one instead of GH_TOKEN
      - name: Generate token
        id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3
        with:
          app-id: ${{ secrets.SEMANTIC_RELEASE_APP_ID }}
          private-key: ${{ secrets.SEMANTIC_RELEASE_PK }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run python-semantic-release
        run: |
          pip install python-semantic-release
          semantic-release version --print > VERSION
          git add VERSION
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install swag v2
        run: go install github.com/swaggo/swag/v2/cmd/swag@latest
      - name: Genrate vmaas-go docs
        run: |
          bash scripts/generate_vmaas_go_docs.sh
          git add vmaas-go/docs/openapi.json
      - name: Submit changes
        run: semantic-release version
        env:
          GH_TOKEN: "${{ steps.app-token.outputs.token }}"
